Ejercicios SQL Dia 1
JaimeLoaiza/ProyectSQL pull request #1
Opened 2019-11-25 05:12 UTC by JaimeLoaiza

Solución Ejercicios SQL 4 y 5.

2019-11-25 21:09 UTC, MauroCaro commented on SQLQueryEjercicio4y5.sql
> +create table Personitas
Es bueno la idea y me parece muy bien la iniciativa,  pero la tabla se debe llamar **Persona** tal como muestra el documento

2019-11-25 21:12 UTC, MauroDecodificado requested changes

2019-11-25 21:12 UTC, MauroCaro commented on SQLQueryEjercicio4y5.sql
> +Select * from Personitas where Nombre = @nombre and Apellido = @apellido and Edad = @edad and Genero = @genero;
El enunciado dice claramente que permita consultar **TODOS** los registros de la tabla, ahi estas haciendo un where basado en los parametros que entran del procedimiento, esta incorrecto.

2019-11-25 21:12 UTC, MauroCaro commented on SQLQueryEjercicio4y5.sql
> +EXEC sp_personas @nombre = 'Mauricio', @apellido = 'CaroG', @edad = 24, @genero = 'Masculino'
Al corregir el where, sus parametros, ya no es necesario añadir los parametros que se envian.

2019-11-25 21:42 UTC, JaimeLoaiza commented
Le tuve que dar ese nombre ya que en un entrar y salir revisando su funcionalidad, ya no me reconocia el nombre de la tabla…
Pero, ok, ya la corrijo

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: MauroCaro<mailto:notifications@github.com>
Enviado: lunes, 25 de noviembre de 2019 4:09 p. m.
Para: JaimeLoaiza/ProyectSQL<mailto:ProyectSQL@noreply.github.com>
CC: JaimeLoaiza<mailto:jaimeloaiza@hotmail.es>; Author<mailto:author@noreply.github.com>
Asunto: Re: [JaimeLoaiza/ProyectSQL] Ejercicios SQL Dia 1 (#1)


@MauroCaro commented on this pull request.


In SQLQueryEjercicio4y5.sql<https://github.com/JaimeLoaiza/ProyectSQL/pull/1#discussion_r350423608>:

> @@ -0,0 +1,20 @@

+use ProyectSQLintensive

+go

+create table Personitas

Es bueno la idea y me parece muy bien la iniciativa, pero la tabla se debe llamar Persona tal como muestra el documento

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/JaimeLoaiza/ProyectSQL/pull/1?email_source=notifications&email_token=ANIHWPE4U6UQ7EA4HIVKLMDQVQ5KDA5CNFSM4JRDQWR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCM5CWRY#pullrequestreview-322579271>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANIHWPCSRL6TEGYWJDN33HLQVQ5KDANCNFSM4JRDQWRQ>.

2019-11-26 16:02 UTC, JaimeLoaiza commented on SQLQueryEjercicio4y5.sql
> +create table Personitas
Correcto, procederé a nombrar correctamente el nombre de la tabla.

2019-11-26 16:09 UTC, JaimeLoaiza commented on SQLQueryEjercicio4y5.sql
> +Select * from Personitas where Nombre = @nombre and Apellido = @apellido and Edad = @edad and Genero = @genero;
La consulta completa de todos los registros es: "SELECT * FROM PERSONAS"

2019-11-26 16:10 UTC, JaimeLoaiza commented on SQLQueryEjercicio4y5.sql
> +EXEC sp_personas @nombre = 'Mauricio', @apellido = 'CaroG', @edad = 24, @genero = 'Masculino'
Realizare los cambios necesarios en la instrucción "SELECT".

2019-11-27 02:58 UTC, MauroDecodificado requested changes

2019-11-27 02:58 UTC, MauroCaro commented on EjerciciosDiaUno.sql
> +create procedure [dbo].[sp_personas] @nombre varchar(50), @apellido varchar(50), @edad int, @genero varchar(10)
Los parametros no se estan usando, por favor eliminalos

2019-11-27 03:11 UTC, MauroDecodificado approved these changes
Approved

2019-11-27 03:13 UTC, merged