Adicionando Archivo EjerciciosDiaDosSQL
JaimeLoaiza/ProyectSQL pull request #2
Opened 2019-11-30 16:21 UTC by JaimeLoaiza

Se unen EjerciciosDiaUno y DiaDos de SQL

2019-11-30 16:32 UTC, MauroDecodificado requested changes
El enunciado dice, realizar **UN** procedimiento almacenado, no dos, ni te estoy pidiendo que consultes cada tabla con todo, por favor lee el ejercicio COMPLETAMENTE que ahi se te indica como se debe solucionar, totalmente incorrecto

2019-11-30 16:32 UTC, MauroCaro commented on EjerciciosDiaDos.sql
> +CREATE TABLE [dbo].[Personas](
Se necesita hacer la relación, donde esta la llave primaria de personas, NO PUEDE SER el campo nombre, ya te mencione cuales son las llaves primarias y que caracteristicas tienen

2019-11-30 16:32 UTC, MauroCaro commented on EjerciciosDiaDos.sql
> +CREATE TABLE [dbo].[Vehiculo](
Dónde esta la llave primaria de vehiculo?

2019-11-30 16:32 UTC, MauroCaro commented on EjerciciosDiaDos.sql
> +ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_NombrePersonas]
Por favor lee el enunciado que dice el ejercicio

Modificar la tabla creada en el ejercicio 1 **llamado Persona** y agregue la **relación con la tabla Vehiculo**, esta relación ​debe ser una persona puede poseer un único vehiculo, uno a uno

2019-11-30 16:32 UTC, MauroCaro commented on EjerciciosDiaDos.sql
> +Select * from Vehiculo;
Leist eel ejercicio? esta solucion esta incorrecta.

2019-11-30 16:32 UTC, MauroCaro commented on EjerciciosDiaDos.sql
> +Select * from Personas;
Leist eel ejercicio? esta solucion esta incorrecta.

2019-11-30 21:24 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +CREATE TABLE [dbo].[Personas](
ok

2019-11-30 21:24 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +CREATE TABLE [dbo].[Vehiculo](
ok

2019-11-30 21:25 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_NombrePersonas]
De Persona a Vehiculo, entendido.

2019-11-30 21:26 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +Select * from Vehiculo;
Reconstruiré la BD.

2019-11-30 21:26 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +Select * from Personas;
Reconstruiré la BD.

2019-12-01 03:51 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +CREATE TABLE [dbo].[Personas](
Correcciones realizadas.

2019-12-01 03:51 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +CREATE TABLE [dbo].[Vehiculo](
Correcciones realizadas.

2019-12-01 03:51 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_NombrePersonas]
Correcciones realizadas.

2019-12-01 03:52 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +Select * from Vehiculo;
Correcciones realizadas.

2019-12-01 03:52 UTC, JaimeLoaiza commented on EjerciciosDiaDos.sql
> +Select * from Personas;
Correcciones realizadas.

2019-12-02 04:43 UTC, MauroDecodificado requested changes

2019-12-02 04:43 UTC, MauroCaro commented on EjerciciosDiaDos.sql
> +Select per.Nombre, per.Apellido, per.Edad, per.Genero, veh.NombreVehiculo, veh.Modelo, veh.Kilometraje, veh.Color FROM [ProyectVisual.Net].[dbo].Persona as per LEFT JOIN [ProyectVisual.Net].dbo.Vehic
El where no es necesario

2019-12-02 15:21 UTC, MauroCaro commented
Probaste el procedimiento almacenado, podrías adjuntar la evidencia de ello en la descripcion del PR?

2019-12-02 15:56 UTC, JaimeLoaiza commented
> Probaste el procedimiento almacenado, podrías adjuntar la evidencia de ello en la descripcion del PR

2019-12-02 17:16 UTC, MauroDecodificado approved these changes
👍 Approved

2019-12-02 17:17 UTC, merged